name: "CI Checks"
description: "Run linting checks for the repository"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.8"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linters
      run: |
        flake8 . --max-line-length=120 --ignore=E501,W503,E203,F401,F403,F405,E722,E731,E741,W504,W605,W601,W602,W604,W606,W607,W608,W609,W610,W611,W612,W613,W614,W615,W616,W617,W618,W619
        black . --check --line-length 120 --skip-string-normalization
