name: "CD Checks"
description: "Run deployment checks for the repository"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.8"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run deployment checks
      shell: bash
      run: |
        # Add your deployment checks here, e.g., running tests, building artifacts, etc.
        echo "Running deployment checks..."
        pytest tests/ --disable-warnings -q
