name: Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run CD Checks
        uses: ./.github/actions/cd-checks

      - name: Deploy to Render
        run: |
          RESPONSE=$(curl -s -w "%{http_code}" -o response.json -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "development",
              "environment": "Preproduction",
              "message": "Deploying from GitHub Actions"
            }')
          cat response.json
          if grep -q '"message":"not found' response.json; then
            echo "Deployment failed: Service not found!"
            exit 1
          elif [ "$RESPONSE" -ge 400 ]; then
            echo "Deployment failed with HTTP status $RESPONSE"
            exit 1
          else
            echo "Deployment successful!"
          fi
