name: Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run CD Checks
        uses: ./.github/actions/cd-checks

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{
            "branch": "development",
            "environment": "preproduction",
            "message": "Deploying from GitHub Actions"
          }'
          if [ $? -ne 0 ]; then
            echo "Deployment failed!"
            exit 1
          else
            echo "Deployment successful!"
          fi