name: Integration
description: "Integration workflow for comum CI checks"

on:
  push:
    branches:
      - main
      - development
      -  feature/*
      -  bugfix/*
      -  hotfix/*
      -  release/*
  pull_request:
    branches:
      - main
      - development
      -  feature/*
      -  bugfix/*
      -  hotfix/*
      -  release/*

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CI Checks
        id: ci-checks
        uses: ./.github/actions/ci-checks

      - name: Check project versioning
        id: check_versioning
        run: |
          echo "Checking project versioning..."
          PROJECT_VERSION=$(cat ./src/__init__.py | grep -oP '(?<=__version__ = ")[^"]*') >> $GITHUB_OUTPUT
          LATEST_TAG=$(git describe --tags --abbrev=0) >> $GITHUB_OUTPUT
          if [[ $PROJECT_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ || $PROJECT_VERSION <= $LATEST_TAG ]]; then
            echo "Please update the project version. Current version: $PROJECT_VERSION, Latest tag: $LATEST_TAG"
            exit 1
          else
            exit 0
          fi

      - name: Workflow resume
        if: ${{ steps.check_versioning.outcome == 'success' && steps.ci-checks.outputs.unit-tests == 'success' }}
        run: | 
            echo "## All checks passed. Proceeding with the workflow."
            echo "## Project version: ${{ steps.check_versioning.outputs.PROJECT_VERSION }}"
            echo "## Latest tag: ${{ steps.check_versioning.outputs.LATEST_TAG }}"
