name: Integration
description: "Integration workflow for comum CI checks"

on:
  push:
    branches:
      - main
      - development
      -  feature/*
      -  bugfix/*
      -  hotfix/*
      -  release/*
  pull_request:
    branches:
      - main
      - development
      -  feature/*
      -  bugfix/*
      -  hotfix/*
      -  release/*

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CI Checks
        id: ci-checks
        uses: ./.github/actions/ci-checks

      - name: Check project versioning
        id: check_versioning
        run: |
          echo "Checking project versioning..."
          PROJECT_VERSION=$(cat ./src/__init__.py | grep -oP '(?<=__version__ = ")[^"]*')
          git fetch --tags --unshallow || git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
          if [ -z "$LATEST_TAG" ]; then
            echo "No git tags found. Please create a tag before running this workflow."
            exit 1
          fi
          if [[ $PROJECT_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ && $PROJECT_VERSION > $LATEST_TAG ]]; then
            exit 0
          else
            echo "Please update the project version. Current version: $PROJECT_VERSION, Latest tag: $LATEST_TAG"
            exit 1
          fi

      - name: Workflow resume
        run: | 
            echo "# Workflow execution results' >> $GITHUB_STEP_SUMMARY
            echo ' - Latest git tag: ${{ steps.check_versioning.outputs.latest_tag }}' >> $GITHUB_STEP_SUMMARY
            echo ' - Project version: ${{ steps.check_versioning.outputs.project_version }}' >> $GITHUB_STEP_SUMMARY
